[package]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "memevis"
repository = "https://github.com/Edgeworth/memevis"
version = "0.1.0"

[dependencies]
derive_more = "0.99.17"
dyn-clone = "1.0.5"
eyre = "0.6.7"
freetype-rs = "0.26.0"
glium = "0.31.0"
harfbuzz_rs = "2.0.1"
log = "0.4.16"
lyon = "0.17.10"
num = "0.4.0"
num-traits = "0.2.14"
paste = "1.0.6"
rgb = "0.8.32"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
tempfile = "3.3.0"
typetag = "0.1.8"

# Build dependencies with optimisations - debug builds will run faster
# but dependencies don't change often.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
