[package]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
edition = "2018"
name = "memevis"
version = "0.1.0"

[dependencies]
chrono = "*"
color-eyre = "*"
derive_more = "*"
eyre = "*"
freetype-rs = "*"
glium = "*"
harfbuzz_rs = "*"
lazy_static = "*"
log = "*"
lyon = "*"
num = "*"
num-traits = "*"
paste = "*"
pretty_env_logger = "*"
prost = "*"
rgb = "*"
serde = {version = "*", features = ["derive"]}
serde_json = "*"
structopt = "*"
tempfile = "*"
tokio = {version = "*", features = ["full"]}
tonic = "*"
typetag = "*"
