[package]
authors = ["Eliot Courtney <edgeworth.dev@gmail.com>"]
edition = "2018"
name = "memevis"
version = "0.1.0"

[dependencies]
derive_more = "*"
dyn-clone = "*"
eyre = "*"
freetype-rs = "*"
glium = "*"
harfbuzz_rs = "*"
lazy_static = "*"
log = "*"
lyon = "*"
num = "*"
num-traits = "*"
parking_lot = "*"
paste = "*"
rgb = "*"
serde = {version = "*", features = ["derive"]}
serde_json = "*"
tempfile = "*"
typetag = "*"
